# Society and water

While contaminants can cause physical health problems, insufficient water supply can cause societal problems. Globally, 1.8 billion people have to travel outside their home to get water. (6) fetching water takes time, and thus that is less time that these people could be spending working or getting educated. Fetching water is a job usually reserved for women and children. If children are working to bring home water, they will not have a chance to attend school which can cause generational ignorance, and perpetuating poverty. This also creates a gender barrier between men and women which goes against SDG 5. (7)


Water availability has implications beyond household dynamics. As mentioned in the introduction, water is used in everything from agriculture to power generation. Therefore, most problems come down to water availability. Countries that have more water have better economies and more stable governments. Try to think of a powerful nation that doesn't have lots of water. Can you think of any? Even the appearingly dry powerhouse Saudi Arabia has vast aquifers that keep them hydrated (at least for now)(8). Countries that are less developed are often riddled with water related problems that hold them down. Most famines are really caused by droughts, and thus their death tool can be attributed to water scarcity. When water is scarce, people wash their hands less frequently and contagious disease spreads more easily. Many areas rely on hydropower, and so the electrical grid is compromised when water levels fall. All these problems will continue to worsen as climate change dries our lakes and melts ice caps, and as we use up all the water from our aquifers. As nations dry up poverty, violence, and sickness will follow.  All these problems seem grim, but there is a way forward. 
