# The way forward

Earlier I asked you if you could think of any powerful countries that don’t have good access to water. Like you, I originally thought that there were none, but I was wrong. While poking through some water data sets (9) I came across an interesting data point. In 2022 the nation of Kuwait withdraws 38.5 times more freshwater than what they could sustainably withdraw. If they were truly withdrawing this much water consistently then they would surely have run dry years ago, but sure enough they had been withdrawing comparable amounts for over 20 years! At first I thought that it must have been a typo, but then I dug into it. Kuwait is a small nation situated on the Persian gulf, with very little freshwater to draw from. They do however have a massive sea that they could drink from if they could find a way to remove the salt, and that's exactly what they did. 

Kuwait is able to provide water to its people through desalination plants that remove salt by distillation or reverse osmosis, and they're not the only ones doing it. (10) The neighboring nations of Qatar, Saudi Arabia, and the UAE are using the same technology to purify the saline seawater. As genius as this strategy is, it is also very energy intensive. Energy however is of no scarcity in these countries, since they lie atop massive oil reserves. As energy generating technology and infrastructure advance in the coming decades, this same desalinization technology will be available to more and more coastal countries. While water sanitation will still remain an issue, water scarcity will no longer be one, and ample water availability will help resolve many issues. I started this story talking about how life emerged from the oceans, and so as we confront the issue of fresh water scarcity we can look back to the ocean for our solutions.  
